language: python
python:
- '2.7'
branches:
  except:
  - gh-pages
install:
- sudo apt-get update -qq > /dev/null
- sudo apt-get -y install inkscape texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
  texlive-xetex texlive-lang-cjk fonts-nanum ttf-wqy-zenhei > /dev/null
- pip install -r requirements.txt > /dev/null
- python setup.py install > /dev/null
- wget http://softcover-binaries.s3.amazonaws.com/kindlegen
- chmod +x ./kindlegen
script: bash ./deploy.sh
sudo: required
dist: trusty
env:
  global:
    secure: jc0kanhtq1w90EizXM4x7dlPhi5q+q8yGg6FriN+81089boCf2PQfLMnhHzBzdzJqzV+Kkb8aLbtwVEvvTvCq7nwIM/qvYRRe6/8ZzyO3Cs1WCFpe0TNUNupgeMYyjUJRbNFVpVMarzDTbLqovaI5QvwSC4y5mkoSd7S7hO5ansB6HRavVH6oZT3UZvGIl24nA8atVSRIf5RrakiVVoU2ZWIukWQs0f8+VR74TlgmrFmDveSLbjpT6KVQaaaABmUCD3uXxFtDljHjNOt1fTAxUcE1kYE9OKl4TUF0aq3R01oO+1U9skmXdpR7RXh9utTun4S06GwS3YOrlTCzGCDhOYON4XULBuP6Db7IaazHBFXImFVuI9kw3AYSVOHoqjL0lmLoXiqQJxcjzCFPp5RkISM8Yp6UHm9OH2RqwNa/2sRCPB0svOzr/rG170SeGGwlo4QnmDni9PpdBPOCiLnbYR1fuWUYsgOLO0VENY916SLNTTVq/jVfw6G0l3YMnl2Ykmhw5hSY15zs5RMDK8XH5eionpKgM5gJXMWcn2a1/Hs3tFrRMPxzwUu8UpjnvEzVawjbCE3wliFhKZD3cvc6miwn+GBwTrqTVKJSwMbRtvs1P16yfJbO0e7bZcikL/RUyDb6BMVlYUOxbCt5hhuc19Nlux34RcL1pljCRecSZE=
